### ISSUE TITLE
Optimise implementation of find command

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#184]
https://github.com/CS2103-AY1819S1-F11-2/main/pull/169

Refer to the comments found in the PR.

Some comments identified by @teowz46 👍  and Codacy  
- It is important to override `hashCode` if you `equals`
- A lot of nested statements in your code

**Comment by JiaqingTan** [comment]
Most of it changed in latest, but will refine others soon.
