### ISSUE TITLE
Select Command does not work on displayed room list

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#193]
The logic for the `select` command applies to the guest list even though the view is a room list.

(1) The selection is displayed correctly, but the message says "selected guest".
![image](https://user-images.githubusercontent.com/24848927/47890288-28ba8b80-de89-11e8-9e52-7b9dc87bfc62.png)

(2) As there are only 4 guests, selecting with an index >4 creates a command exception.
![image](https://user-images.githubusercontent.com/24848927/47890309-44259680-de89-11e8-8dcf-64ca83966105.png)

The logic is checking the validity of selection using the guest list.
![image](https://user-images.githubusercontent.com/24848927/47890332-5c95b100-de89-11e8-903c-53ac23360235.png)

**Comment by adamwth** [comment]
fixed in #211
