### ISSUE TITLE
Implement edit room command

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#217]
Command format:

`edit -r [C/ CAPACITY] [T/TAGS]`

- include a flag to indicate it is editing a room
- capacity and tags and optional fields

**Comment by adamwth** [comment]
// edit room capacity
`edit r/001 nc/1`

// edit room tags
`edit r/001 nt/vip nt/specialneeds`

// edit booking period of booking in room
`edit r/001 from/05/11/18 nfrom/09/11/18`
`edit r/001 from/05/11/18 nfrom/09/11/18 nto/11/11/18`

// edit guest of booking in room
`edit r/001 from/05/11/18 nn/Popo np/999 ne/popo@spf.com nt/vip`

// edit guest across all bookings in room
`edit r/001 n/John p/123 nn/Popo np/999 ne/popo@spf.com nt/vip`

// edit guest across all bookings in all rooms
`edit n/John p/123 nn/Popo np/999 ne/popo@spf.com nt/vip`

**Comment by pikulet** [comment]
Closed. Moved to https://github.com/CS2103-AY1819S1-F11-2/main/issues/231
