### ISSUE TITLE
Unclear which guest is added upon checkin and checkout

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#240]
Suppose a `Guest` uses two different phone number and has different tags on two bookings. The current implementation merely retains the first instance of the `Guest` added in either the `uniqueGuestList` or `uniqueCheckedInGuestList`

**Comment by pikulet** [comment]
`add n/John p/123 e/john@test.com r/005 from/12/11/2018 to/13/11/2018`
`add n/John p/456 t/VIP e/john@test.com r/006 from/12/11/2018 to/13/11/2018`

`checkin r/005` adds John with phone number 123 to the checkedInGuestList.
`checkin r/006` John's phone number not updated. Tags not updated.

Is this the intended behaviour? Would be good to document in the user guide.

**Comment by adamwth** [comment]
@pikulet yup, that is the intended behavior. Good catch!

Clarified in #257.
