### ISSUE TITLE
Room Check-Out / Maintenance v1.1

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#56]
Archive - History of guests (Guest object plus start and end Dates)
Implement CheckoutCommand (option for whole room or certain guests)
Retain Delete Command
Delete from GuestList

**Comment by adamwth** [comment]
See #71 and #78 for more details on added functionality.
In a nutshell, 
- Room package and associated classes/exceptions have been added to lay the groundwork for _Concierge_. 
- `checkout` feature has been implemented across the system, including the command, parser and methods in the Room classes. 
- More tests need to be created and checked for the newly added classes.
- ArchivedGuestList is to be implemented after v1.1.

**Comment by pikulet** [comment]
This has been moved to Milestone v1.3
