### ISSUE TITLE
Learn and incorporate JavaFX in your feature

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#61]
Since GUI is consistently used across all features, it is important for everyone to have an idea of how GUI works. Minimally, provide the API needed for JavaFX to access.

Seek help from @JiaqingTan if needed.

**Comment by adamwth** [comment]
Priority has been shifted to UI functionality, rather than design. This means that Concierge's core logic will be implemented using AddressBook4's UI first, then redesigned to match the UI mockup afterwards.
