### ISSUE TITLE
Renaming addressBookFilePath to guestListFilePath in UserPrefs.java fails the JsonUserPrefsStorageTest

### ISSUE THREAD

**Issue by pikulet** [CS2103-AY1819S1-F11-2/main#70]
`src\main\java\seedu\address\model\UserPrefs.java` has a `Path` variable named `addressBookFilePath`.

I tried renaming this to `guestListFilePath`, passing all checks on my local repo.
However, these checks fail on Travis CI.

**Comment by adamwth** [comment]
Can you give some examples?

**Comment by pikulet** [comment]
Failed test cases from JsonUserPrefsStorageTest

public void readUserPrefs_extraValuesInFile_extraValuesIgnored() throws DataConversionException
- opens ExtraValuesUserPref.json

public void readUserPrefs_fileInOrder_successfullyRead() throws DataConversionException {
- opens TypicalUserPref.json

These are the only two test cases which involve opening a valid UserPref.json file.
However, renaming addressBookFilePath to guestListFilePath in UserPrefs.java results in these test cases failing on **Travis CI**.

**Assertion Error did not turn up in local repo.**
See this closed PR: https://github.com/CS2103-AY1819S1-F11-2/main/pull/55
commit 6880b28: JsonUserPrefsStorageTest: renamed filepath in test json files
This commit passes all test cases on my local repo.

**Comment by pikulet** [comment]
@teowz46 If you encounter this problem, it's because the file `src/test/data/` is untracked by `.gitignore`.

If you rename any of the files, remember to add them using `git add -f <file>`
